"""empty message

Revision ID: 861de49b55b7
Revises: bae5964eea7b
Create Date: 2020-03-11 21:24:23.546859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861de49b55b7'
down_revision = 'bae5964eea7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Good', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('order', sa.Column('login', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'login')
    op.drop_column('Good', 'link')
    # ### end Alembic commands ###
