"""empty message

Revision ID: bae5964eea7b
Revises: 550f90e9d49d
Create Date: 2020-03-07 20:05:42.019849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae5964eea7b'
down_revision = '550f90e9d49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wayOfPaiment', sa.String(length=128), nullable=True),
    sa.Column('oddMoney', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('porch', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=128), nullable=True),
    sa.Column('apartment', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('firstName', sa.String(length=128), nullable=True),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
